### PR TITLE
Update Rust.sublime-build

### PR DESCRIPTION
**Pull request by lienmeat**
Added rust paths for linux (tested in ubuntu 15.04)

### CODE REVIEW

**Comment by jhasse** [comment]
Hm ... why do these paths need to be added?

Maybe cmd should be changed into shell_cmd instead?

**Comment by lienmeat** [comment]
Possibly, idk.  I haven't messed with sublime builds much. I was just
trying to make it work on my system.

**Comment by jhasse** [comment]
Can you try?

Because this patch isn't needed for me to have Rust working on Linux (Linux Mint 17.1). The hard-coded path is there for OSX, because I don't care about that OS.

**Comment by lienmeat** [comment]
I hope to have time this evening to mess with it more.  Perhaps something
is/was wrong with my $PATH to make this necessary for it to work or
something.

**Comment by lienmeat** [comment]
I got around to messing with this more.  As I suspected, my $PATH was
messed up.  Sorry for the trouble.  You can safely ignore this commit.

**Pull request closed without merging**
