### PR TITLE
Added the `move` keyword

### PR DESCRIPTION
**Pull request by bonifaido**

### CODE REVIEW

**Comment by jhasse** [comment]
You also need to generate the .tmLanguage file. See the README.md

**Comment by bonifaido** [comment]
Done it.

**Comment by jhasse** [comment]
Thanks :)

Btw: You can squash commits using `git commit --amend`. Also try to use imperative present tense in the commit message, see http://git-scm.com/book/ch5-2.html

**Comment by bonifaido** [comment]
Great, maybe next time! Thanks :)

**Pull request merged**
