### PR TITLE
Add `isize` and `usize` types

### PR DESCRIPTION
**Pull request by loyd**
[The decision.](https://github.com/rust-lang/rfcs/pull/544#issuecomment-68760871)

### CODE REVIEW

**Comment by jhasse** [comment]
Thanks! The `.tmLanguage` is generated using AAAPackageDev though. I've added your changes in the JSON file, too.

**Comment by brookst** [comment]
When is it planned to remove the `int`/`uint` and `i`/`u` terms from this highlighter?

It was suggested to remove them immediately from the vim syntax highlighter (rust-lang/rust#20881), as this shows their deprecation.

Also, when does this get pushed up to [github/linguist](https://github.com/github/linguist)?

Thanks.

**Comment by jhasse** [comment]
Good idea. If someone opens a PR I will merge it right away, otherwise I
will do it in the following weeks ;)

Don't know about linguist. Are they using this plugin?

**Comment by brookst** [comment]
Yeah, I got here from linguist. This plugin is linked as a submodule in https://github.com/github/linguist/tree/master/vendor/grammars. I assume that means githubs syntax highlighting is using this plugin.

I'm not a Sublime Text user, so I don't really want to start hacking at it without a way to test.

**Comment by loyd** [comment]
@jhasse I think we should wait a little bit, at least until the beta version of Rust.

**Pull request closed without merging**
